var modules =
[
    [ "Allocator", "group__EV__ALLOCATOR.html", "group__EV__ALLOCATOR" ],
    [ "Async", "group__EV__ASYNC.html", "group__EV__ASYNC" ],
    [ "Defines", "group__EV__DEFINE.html", "group__EV__DEFINE" ],
    [ "Error number", "group__EV__ERRNO.html", "group__EV__ERRNO" ],
    [ "File System", "group__EV__FILESYSTEM.html", "group__EV__FILESYSTEM" ],
    [ "Handle", "group__EV__HANDLE.html", "group__EV__HANDLE" ],
    [ "List", "group__EV__UTILS__LIST.html", "group__EV__UTILS__LIST" ],
    [ "Event loop", "group__EV__EVENT__LOOP.html", "group__EV__EVENT__LOOP" ],
    [ "Map", "group__EV__UTILS__MAP.html", "group__EV__UTILS__MAP" ],
    [ "Miscellaneous utilities", "group__EV__MISC.html", "group__EV__MISC" ],
    [ "Mutex", "group__EV__MUTEX.html", "group__EV__MUTEX" ],
    [ "Once", "group__EV__ONCE.html", "group__EV__ONCE" ],
    [ "Pipe", "group__EV__PIPE.html", "group__EV__PIPE" ],
    [ "Process", "group__EV__PROCESS.html", "group__EV__PROCESS" ],
    [ "Queue", "group__EV__UTILS__QUEUE.html", "group__EV__UTILS__QUEUE" ],
    [ "Semaphore", "group__EV__SEMAPHORE.html", "group__EV__SEMAPHORE" ],
    [ "Shared library", "group__EV__SHAREDLIBRARY.html", "group__EV__SHAREDLIBRARY" ],
    [ "Shared memory", "group__EV__SHARED__MEMORY.html", "group__EV__SHARED__MEMORY" ],
    [ "TCP", "group__EV__TCP.html", "group__EV__TCP" ],
    [ "Thread", "group__EV__Thread.html", "group__EV__Thread" ],
    [ "Time", "group__EV__TIME.html", "group__EV__TIME" ],
    [ "Timer", "group__EV__TIMER.html", "group__EV__TIMER" ],
    [ "UDP", "group__EV__UDP.html", "group__EV__UDP" ],
    [ "Version", "group__EV__VERSION.html", "group__EV__VERSION" ]
];