#define EV_AMALGAMATE_BUILD
#define EV_BUILDING_DLL
#define _GNU_SOURCE
#include "ev.h" /* @AMALGAMATE: SKIP */

#include "ev/assert_internal.h"
#include "ev/defs.h"
#include "ev/async_internal.h"
#include "ev/handle_internal.h"
#include "ev/loop_internal.h"
#include "ev/fs_internal.h"
#include "ev/misc_internal.h"
#include "ev/pipe_internal.h"
#include "ev/ringbuffer.h"
#include "ev/threadpool.h"
#include "ev/timer_internal.h"
#include "ev/log.h"
#include "ev/udp_internal.h"

#include "ev/assert.c"
#include "ev/allocator.c"
#include "ev/errno.c"
#include "ev/fs.c"
#include "ev/handle.c"
#include "ev/list.c"
#include "ev/log.c"
#include "ev/loop.c"
#include "ev/map.c"
#include "ev/misc.c"
#include "ev/pipe.c"
#include "ev/queue.c"
#include "ev/ringbuffer.c"
#include "ev/shmem.c"
#include "ev/threadpool.c"
#include "ev/timer.c"
#include "ev/udp.c"
#include "ev/version.c"

#if defined(_WIN32)

#   include "ev/win/winapi.h"
#   include "ev/win/winsock.h"
#   include "ev/win/async_win.h"
#   include "ev/win/fs_win.h"
#   include "ev/win/time_win.h"
#   include "ev/win/udp_win.h"
#   include "ev/win/loop_win.h"
#   include "ev/win/process_win.h"
#   include "ev/win/pipe_win.h"
#   include "ev/win/misc_win.h"
#   include "ev/win/thread_win.h"
#   include "ev/win/threadpool_win.h"
#   include "ev/win/tcp_win.h"

#   include "ev/win/async_win.c"
#   include "ev/win/fs_win.c"
#   include "ev/win/loop_win.c"
#   include "ev/win/misc_win.c"
#   include "ev/win/mutex_win.c"
#   include "ev/win/once_win.c"
#   include "ev/win/pipe_win.c"
#   include "ev/win/process_win.c"
#   include "ev/win/sem_win.c"
#   include "ev/win/shdlib_win.c"
#   include "ev/win/shmem_win.c"
#   include "ev/win/tcp_win.c"
#   include "ev/win/thread_win.c"
#   include "ev/win/threadpool_win.c"
#   include "ev/win/time_win.c"
#   include "ev/win/udp_win.c"
#   include "ev/win/winapi.c"
#   include "ev/win/winsock.c"

#else

#   include "ev/unix/async_unix.h"
#   include "ev/unix/io_unix.h"
#   include "ev/unix/process_unix.h"
#   include "ev/unix/tcp_unix.h"
#   include "ev/unix/loop_unix.h"
#   include "ev/unix/misc_unix.h"
#   include "ev/unix/stream_unix.h"
#   include "ev/unix/work.h"

#   include "ev/unix/async_unix.c"
#   include "ev/unix/fs_unix.c"
#   include "ev/unix/io_unix.c"
#   include "ev/unix/loop_unix.c"
#   include "ev/unix/misc_unix.c"
#   include "ev/unix/mutex_unix.c"
#   include "ev/unix/once_unix.c"
#   include "ev/unix/pipe_unix.c"
#   include "ev/unix/process_unix.c"
#   include "ev/unix/sem_unix.c"
#   include "ev/unix/shdlib_unix.c"
#   include "ev/unix/shmem_unix.c"
#   include "ev/unix/stream_unix.c"
#   include "ev/unix/tcp_unix.c"
#   include "ev/unix/thread_unix.c"
#   include "ev/unix/threadpool_unix.c"
#   include "ev/unix/time_unix.c"
#   include "ev/unix/udp_unix.c"

#endif
